/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlarmsAndCctvRouteImport } from './routes/alarms-and-cctv'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as Control4GlasgowRouteImport } from './routes/control4-glasgow'
import { Route as DataNetworkingAndWifiRouteImport } from './routes/data-networking-and-wifi'
import { Route as DoorEntryAndAccessRouteImport } from './routes/door-entry-and-access'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HomeAutomationGlasgowRouteImport } from './routes/home-automation-glasgow'
import { Route as HomeCinemaRouteImport } from './routes/home-cinema'
import { Route as LutronGlasgowRouteImport } from './routes/lutron-glasgow'
import { Route as MultiRoomAudioAndVideoRouteImport } from './routes/multi-room-audio-and-video'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SmartHomeForArchitectsRouteImport } from './routes/smart-home-for-architects'
import { Route as SmartHomeForInteriorDesignersRouteImport } from './routes/smart-home-for-interior-designers'
import { Route as SmartHomeGlasgowRouteImport } from './routes/smart-home-glasgow'
import { Route as SmartLightingGlasgowRouteImport } from './routes/smart-lighting-glasgow'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsWhitecraigsGlasgowRouteImport } from './routes/projects.whitecraigs-glasgow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsAndCctvRoute = AlarmsAndCctvRouteImport.update({
  id: '/alarms-and-cctv',
  path: '/alarms-and-cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Control4GlasgowRoute = Control4GlasgowRouteImport.update({
  id: '/control4-glasgow',
  path: '/control4-glasgow',
  getParentRoute: () => rootRouteImport,
} as any)
const DataNetworkingAndWifiRoute = DataNetworkingAndWifiRouteImport.update({
  id: '/data-networking-and-wifi',
  path: '/data-networking-and-wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorEntryAndAccessRoute = DoorEntryAndAccessRouteImport.update({
  id: '/door-entry-and-access',
  path: '/door-entry-and-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAutomationGlasgowRoute = HomeAutomationGlasgowRouteImport.update({
  id: '/home-automation-glasgow',
  path: '/home-automation-glasgow',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCinemaRoute = HomeCinemaRouteImport.update({
  id: '/home-cinema',
  path: '/home-cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const LutronGlasgowRoute = LutronGlasgowRouteImport.update({
  id: '/lutron-glasgow',
  path: '/lutron-glasgow',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoomAudioAndVideoRoute = MultiRoomAudioAndVideoRouteImport.update({
  id: '/multi-room-audio-and-video',
  path: '/multi-room-audio-and-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeForArchitectsRoute = SmartHomeForArchitectsRouteImport.update({
  id: '/smart-home-for-architects',
  path: '/smart-home-for-architects',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeForInteriorDesignersRoute =
  SmartHomeForInteriorDesignersRouteImport.update({
    id: '/smart-home-for-interior-designers',
    path: '/smart-home-for-interior-designers',
    getParentRoute: () => rootRouteImport,
  } as any)
const SmartHomeGlasgowRoute = SmartHomeGlasgowRouteImport.update({
  id: '/smart-home-glasgow',
  path: '/smart-home-glasgow',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartLightingGlasgowRoute = SmartLightingGlasgowRouteImport.update({
  id: '/smart-lighting-glasgow',
  path: '/smart-lighting-glasgow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsWhitecraigsGlasgowRoute =
  ProjectsWhitecraigsGlasgowRouteImport.update({
    id: '/whitecraigs-glasgow',
    path: '/whitecraigs-glasgow',
    getParentRoute: () => ProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alarms-and-cctv': typeof AlarmsAndCctvRoute
  '/contact': typeof ContactRoute
  '/control4-glasgow': typeof Control4GlasgowRoute
  '/data-networking-and-wifi': typeof DataNetworkingAndWifiRoute
  '/door-entry-and-access': typeof DoorEntryAndAccessRoute
  '/faq': typeof FaqRoute
  '/home-automation-glasgow': typeof HomeAutomationGlasgowRoute
  '/home-cinema': typeof HomeCinemaRoute
  '/lutron-glasgow': typeof LutronGlasgowRoute
  '/multi-room-audio-and-video': typeof MultiRoomAudioAndVideoRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-home-for-architects': typeof SmartHomeForArchitectsRoute
  '/smart-home-for-interior-designers': typeof SmartHomeForInteriorDesignersRoute
  '/smart-home-glasgow': typeof SmartHomeGlasgowRoute
  '/smart-lighting-glasgow': typeof SmartLightingGlasgowRoute
  '/projects/whitecraigs-glasgow': typeof ProjectsWhitecraigsGlasgowRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alarms-and-cctv': typeof AlarmsAndCctvRoute
  '/contact': typeof ContactRoute
  '/control4-glasgow': typeof Control4GlasgowRoute
  '/data-networking-and-wifi': typeof DataNetworkingAndWifiRoute
  '/door-entry-and-access': typeof DoorEntryAndAccessRoute
  '/faq': typeof FaqRoute
  '/home-automation-glasgow': typeof HomeAutomationGlasgowRoute
  '/home-cinema': typeof HomeCinemaRoute
  '/lutron-glasgow': typeof LutronGlasgowRoute
  '/multi-room-audio-and-video': typeof MultiRoomAudioAndVideoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-home-for-architects': typeof SmartHomeForArchitectsRoute
  '/smart-home-for-interior-designers': typeof SmartHomeForInteriorDesignersRoute
  '/smart-home-glasgow': typeof SmartHomeGlasgowRoute
  '/smart-lighting-glasgow': typeof SmartLightingGlasgowRoute
  '/projects/whitecraigs-glasgow': typeof ProjectsWhitecraigsGlasgowRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alarms-and-cctv': typeof AlarmsAndCctvRoute
  '/contact': typeof ContactRoute
  '/control4-glasgow': typeof Control4GlasgowRoute
  '/data-networking-and-wifi': typeof DataNetworkingAndWifiRoute
  '/door-entry-and-access': typeof DoorEntryAndAccessRoute
  '/faq': typeof FaqRoute
  '/home-automation-glasgow': typeof HomeAutomationGlasgowRoute
  '/home-cinema': typeof HomeCinemaRoute
  '/lutron-glasgow': typeof LutronGlasgowRoute
  '/multi-room-audio-and-video': typeof MultiRoomAudioAndVideoRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-home-for-architects': typeof SmartHomeForArchitectsRoute
  '/smart-home-for-interior-designers': typeof SmartHomeForInteriorDesignersRoute
  '/smart-home-glasgow': typeof SmartHomeGlasgowRoute
  '/smart-lighting-glasgow': typeof SmartLightingGlasgowRoute
  '/projects/whitecraigs-glasgow': typeof ProjectsWhitecraigsGlasgowRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alarms-and-cctv'
    | '/contact'
    | '/control4-glasgow'
    | '/data-networking-and-wifi'
    | '/door-entry-and-access'
    | '/faq'
    | '/home-automation-glasgow'
    | '/home-cinema'
    | '/lutron-glasgow'
    | '/multi-room-audio-and-video'
    | '/projects'
    | '/sitemap.xml'
    | '/smart-home-for-architects'
    | '/smart-home-for-interior-designers'
    | '/smart-home-glasgow'
    | '/smart-lighting-glasgow'
    | '/projects/whitecraigs-glasgow'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alarms-and-cctv'
    | '/contact'
    | '/control4-glasgow'
    | '/data-networking-and-wifi'
    | '/door-entry-and-access'
    | '/faq'
    | '/home-automation-glasgow'
    | '/home-cinema'
    | '/lutron-glasgow'
    | '/multi-room-audio-and-video'
    | '/sitemap.xml'
    | '/smart-home-for-architects'
    | '/smart-home-for-interior-designers'
    | '/smart-home-glasgow'
    | '/smart-lighting-glasgow'
    | '/projects/whitecraigs-glasgow'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alarms-and-cctv'
    | '/contact'
    | '/control4-glasgow'
    | '/data-networking-and-wifi'
    | '/door-entry-and-access'
    | '/faq'
    | '/home-automation-glasgow'
    | '/home-cinema'
    | '/lutron-glasgow'
    | '/multi-room-audio-and-video'
    | '/projects'
    | '/sitemap.xml'
    | '/smart-home-for-architects'
    | '/smart-home-for-interior-designers'
    | '/smart-home-glasgow'
    | '/smart-lighting-glasgow'
    | '/projects/whitecraigs-glasgow'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlarmsAndCctvRoute: typeof AlarmsAndCctvRoute
  ContactRoute: typeof ContactRoute
  Control4GlasgowRoute: typeof Control4GlasgowRoute
  DataNetworkingAndWifiRoute: typeof DataNetworkingAndWifiRoute
  DoorEntryAndAccessRoute: typeof DoorEntryAndAccessRoute
  FaqRoute: typeof FaqRoute
  HomeAutomationGlasgowRoute: typeof HomeAutomationGlasgowRoute
  HomeCinemaRoute: typeof HomeCinemaRoute
  LutronGlasgowRoute: typeof LutronGlasgowRoute
  MultiRoomAudioAndVideoRoute: typeof MultiRoomAudioAndVideoRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartHomeForArchitectsRoute: typeof SmartHomeForArchitectsRoute
  SmartHomeForInteriorDesignersRoute: typeof SmartHomeForInteriorDesignersRoute
  SmartHomeGlasgowRoute: typeof SmartHomeGlasgowRoute
  SmartLightingGlasgowRoute: typeof SmartLightingGlasgowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms-and-cctv': {
      id: '/alarms-and-cctv'
      path: '/alarms-and-cctv'
      fullPath: '/alarms-and-cctv'
      preLoaderRoute: typeof AlarmsAndCctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control4-glasgow': {
      id: '/control4-glasgow'
      path: '/control4-glasgow'
      fullPath: '/control4-glasgow'
      preLoaderRoute: typeof Control4GlasgowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-networking-and-wifi': {
      id: '/data-networking-and-wifi'
      path: '/data-networking-and-wifi'
      fullPath: '/data-networking-and-wifi'
      preLoaderRoute: typeof DataNetworkingAndWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/door-entry-and-access': {
      id: '/door-entry-and-access'
      path: '/door-entry-and-access'
      fullPath: '/door-entry-and-access'
      preLoaderRoute: typeof DoorEntryAndAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-automation-glasgow': {
      id: '/home-automation-glasgow'
      path: '/home-automation-glasgow'
      fullPath: '/home-automation-glasgow'
      preLoaderRoute: typeof HomeAutomationGlasgowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-cinema': {
      id: '/home-cinema'
      path: '/home-cinema'
      fullPath: '/home-cinema'
      preLoaderRoute: typeof HomeCinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lutron-glasgow': {
      id: '/lutron-glasgow'
      path: '/lutron-glasgow'
      fullPath: '/lutron-glasgow'
      preLoaderRoute: typeof LutronGlasgowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-room-audio-and-video': {
      id: '/multi-room-audio-and-video'
      path: '/multi-room-audio-and-video'
      fullPath: '/multi-room-audio-and-video'
      preLoaderRoute: typeof MultiRoomAudioAndVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home-for-architects': {
      id: '/smart-home-for-architects'
      path: '/smart-home-for-architects'
      fullPath: '/smart-home-for-architects'
      preLoaderRoute: typeof SmartHomeForArchitectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home-for-interior-designers': {
      id: '/smart-home-for-interior-designers'
      path: '/smart-home-for-interior-designers'
      fullPath: '/smart-home-for-interior-designers'
      preLoaderRoute: typeof SmartHomeForInteriorDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home-glasgow': {
      id: '/smart-home-glasgow'
      path: '/smart-home-glasgow'
      fullPath: '/smart-home-glasgow'
      preLoaderRoute: typeof SmartHomeGlasgowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-lighting-glasgow': {
      id: '/smart-lighting-glasgow'
      path: '/smart-lighting-glasgow'
      fullPath: '/smart-lighting-glasgow'
      preLoaderRoute: typeof SmartLightingGlasgowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/whitecraigs-glasgow': {
      id: '/projects/whitecraigs-glasgow'
      path: '/whitecraigs-glasgow'
      fullPath: '/projects/whitecraigs-glasgow'
      preLoaderRoute: typeof ProjectsWhitecraigsGlasgowRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsWhitecraigsGlasgowRoute: typeof ProjectsWhitecraigsGlasgowRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsWhitecraigsGlasgowRoute: ProjectsWhitecraigsGlasgowRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlarmsAndCctvRoute: AlarmsAndCctvRoute,
  ContactRoute: ContactRoute,
  Control4GlasgowRoute: Control4GlasgowRoute,
  DataNetworkingAndWifiRoute: DataNetworkingAndWifiRoute,
  DoorEntryAndAccessRoute: DoorEntryAndAccessRoute,
  FaqRoute: FaqRoute,
  HomeAutomationGlasgowRoute: HomeAutomationGlasgowRoute,
  HomeCinemaRoute: HomeCinemaRoute,
  LutronGlasgowRoute: LutronGlasgowRoute,
  MultiRoomAudioAndVideoRoute: MultiRoomAudioAndVideoRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartHomeForArchitectsRoute: SmartHomeForArchitectsRoute,
  SmartHomeForInteriorDesignersRoute: SmartHomeForInteriorDesignersRoute,
  SmartHomeGlasgowRoute: SmartHomeGlasgowRoute,
  SmartLightingGlasgowRoute: SmartLightingGlasgowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
